# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Reference Integration Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  integration:
    # TODO: restore job once fixed. https://github.com/eclipse-score/lifecycle/issues/84
    if: false
    uses: eclipse-score/reference_integration/.github/workflows/reusable_smoke-test.yml@main
    secrets: inherit
    with:
      repo_runner_labels: 'ubuntu-latest'
      module_name: 'score_lifecycle_health'
      target_branch: 'main'
